import type { Metadata } from "next";
import React from "react";
import Header from "@/components/Header/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={''}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
